variables:
  REPOSITORY_URL: 312583731641.dkr.ecr.eu-central-1.amazonaws.com/roomook/roomook-frontend

services:
  - docker:dind

stages:
  - build
  - deploy

before_script:
  - apk add --no-cache curl jq python py-pip bash
  - pip install awscli
  - export VERSION=$(date +%F)-${CI_COMMIT_SHA:0:9}
  - cd ${CI_PROJECT_DIR}

build:
  stage: build
  tags:
    - docker
  image: docker:latest
  script:
    - docker build --tag ${REPOSITORY_URL}:${VERSION} .
  except:
    - master@development/roomook.frontend

build_and_upload:
  stage: build
  tags:
    - docker
  image: docker:latest
  script:
    - $(aws ecr get-login --no-include-email --region eu-central-1)
    - docker build --tag ${REPOSITORY_URL}:${VERSION} .
    - docker push ${REPOSITORY_URL}:${VERSION}
  only:
    - master@development/roomook.frontend

deploy:
  stage: deploy
  tags:
    - docker
  image: docker:latest
  script:
    - ./deploy.sh -s 2 -v ${VERSION} -e prod
  only:
    - master@development/roomook.frontend
